# Site settings
author: Ty Raino 👑
title: Coding Journey
header-img: img/home-bg.png
email: mstymetris@yahoo.com
copyright_name: Ty Raino 👑
description: > # this means to ignore newlines until "baseurl:"
  Can't wait to see what the future holds!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: fillthecrown_
github_username:  ty-raino

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
