# Site settings
author: ty raino
title: blog
header-img: img/home-bg.png
email: mstymetris@yahoo.com
copyright_name: ty raino
description: > # this means to ignore newlines until "baseurl:"
  blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ty-raino

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
